name: Jurimetria ETL

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  etl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - run: pip install -r requirements.txt

      - name: Run jurimetria pipeline
        env:
          CNJ_API_KEY: ${{ secrets.CNJ_API_KEY }}
        run: |
          python src/jurimetria_pipeline.py \
            --tribunais TJCE \
            --de 2023-01-01 \
            --ate 2023-02-28 \
            --max-processos 200 \
            --log-level DEBUG

      - name: Listar arquivos criados
        run: |
          ls -lR dados_jurimetria || echo "Diretório não existe"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dados-jurimetria
          path: dados_jurimetria/**
