name: Jurimetria ETL

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # 1) Job de Testes
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pytest
        run: pytest -q

  # 2) Job ETL (depende de test)
  etl:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run jurimetria pipeline
        env:
          CNJ_API_KEY: ${{ secrets.CNJ_API_KEY }}
        run: |
          python src/jurimetria_pipeline.py \
            --tribunais TJCE \
            --de 2023-01-01 \
            --ate 2023-01-31 \
            --max-processos 100

      - name: Debug: mostre o que foi gerado
        run: |
          echo "=== Onde estou ==="
          pwd
          echo "=== Conteúdo do workspace ==="
          ls -R .
          echo "=== Conteúdo de dados_jurimetria ==="
          ls -R dados_jurimetria || echo "pasta dados_jurimetria não existe"

      - name: Debug ETL outputs
        run: |
          echo "=== Preview do CSV (até 20 linhas) ==="
          head -n 20 dados_jurimetria/jurimetria.csv || echo "sem CSV"
          echo
          echo "=== Preview do Parquet ==="
          ls -lh dados_jurimetria/jurimetria.parquet || echo "sem Parquet"
          echo
          echo "=== Imagem gerada ==="
          ls -lh dados_jurimetria/horario_jurimetria.jpg || echo "sem imagem"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dados-jurimetria
          path: |
            dados_jurimetria/**
