name: Jurimetria ETL

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  etl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run jurimetria pipeline
        env:
          CNJ_API_KEY: ${{ secrets.CNJ_API_KEY }}
        run: |
          python src/jurimetria_pipeline.py \
            --tribunais TJCE \
            --de 2023-01-01 \
            --ate 2023-01-31 \
            --max-processos 100 \
            --log-level DEBUG

      - name: Debug: liste o conteúdo de saída
        run: |
          echo ">>> Estou em: $(pwd)"
          echo ">>> Conteúdo do workspace:"
          ls -l .
          echo ">>> Conteúdo da pasta dados_jurimetria:"
          ls -lh dados_jurimetria || echo ">> pasta vazia ou não existe"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dados-jurimetria
          path: dados_jurimetria/**
