name: Jurimetria ETL

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run pytest
        run: pytest -q

  etl:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run jurimetria pipeline
        env:
          CNJ_API_KEY: ${{ secrets.CNJ_API_KEY }}
        run: |
          python src/jurimetria_pipeline.py \
            --tribunais TJCE \
            --de 2023-01-01 \
            --ate 2023-01-31 \
            --max-processos 100 \
            --log-level DEBUG

      - name: Debug: listar saída
        run: |
          echo ">> pwd: $(pwd)"
          echo ">> Conteúdo raiz:"
          ls -l .
          echo ">> Conteúdo pasta dados_jurimetria:"
          ls -l dados_jurimetria || echo "pasta dados_jurimetria não existe"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dados-jurimetria
          path: dados_jurimetria/**
