jobs:
  etl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - run: pip install -r requirements.txt

      - name: Run jurimetria pipeline
        env:
          CNJ_API_KEY: ${{ secrets.CNJ_API_KEY }}
        run: |
          python src/jurimetria_pipeline.py \
            --tribunais TJCE \
            --de 2023-01-01 \
            --ate 2023-01-31 \
            --max-processos 100 \
            --log-level DEBUG

      - name: Debug: liste o workspace e a pasta de saída
        run: |
          echo ">> pwd: $(pwd)"
          echo ">> root contents:"
          ls -l .
          echo ">> dados_jurimetria contents:"
          ls -l dados_jurimetria || echo ">> pasta não existe ou está vazia"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dados-jurimetria
          path: dados_jurimetria/**
