diff --git a//dev/null b/.github/workflows/tests.yml
index 0000000000000000000000000000000000000000..b7dcbccf166e88ea6db1da058c3e84a0e82f4b14 100644
--- a//dev/null
+++ b/.github/workflows/tests.yml
@@ -0,0 +1,21 @@
+name: Testes
+
+on:
+  push:
+    branches: [main]
+  pull_request:
+
+jobs:
+  test:
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: actions/checkout@v4
+      - uses: actions/setup-python@v5
+        with:
+          python-version: '3.11'
+          cache: 'pip'
+      - - name: Install dependencies
  run: pip install -r requirements.txt
- name: Install pytest
  run: pip install pytest
- name: Run pytest
  run: pytest -q